### ISSUE TITLE
Error loading coins

### ISSUE THREAD

**Issue by johnnyasantoss** [bob6664569/blockfolio-api-client#1]
Hello!
I've found a problem in the `_refreshCoins` function.
As it uses the `aliasTokenSymbol` to make the aggregation of bases it expects that this value is always the same.
I found that it is not true for all coins, see the DASH example: 

    {
      "base": "BTC",
      "standardTokenSymbol": "DASH",
      "displayedTokenSymbol": "DASH",
      "aliasTokenSymbol": "DSH",
      "fullName": "Dash"
    },
    {
      "base": "PLN",
      "standardTokenSymbol": "DASH",
      "displayedTokenSymbol": "DASH",
      "aliasTokenSymbol": "DASH",
      "fullName": "Dash"
    },
    {
      "base": "KRW",
      "standardTokenSymbol": "DASH",
      "displayedTokenSymbol": "DASH",
      "aliasTokenSymbol": "DASH",
      "fullName": "Dash"
    }

**Comment by bob6664569** [comment]
It seems that this issue is not yet closed... Now I got some pairs with `use_alias` which aren't matched anymore this way (IOTA, EUR*, ...). Will need some tests for that. Maybe should use the `standardTokenSymbol` instead (the app uses aliases everywhere, that's why I used them this way)

**Comment by johnnyasantoss** [comment]
I was thinking that it would be nice if it could make a lookup in a alias array :)
This way we don't have problems with the `standardTokenSymbol` that is only a standard in the blockfolio app, not in the exchanges.

**Comment by bob6664569** [comment]
Just tested, and still a no for IOTA. Plus, there are symbols that are concerning several tokens.... IE. XBT (Bitcoin on Bitmex,... but BrickTox on other exchanges...). I'll try to store the full list returned by Blockfolio, then rework the _validateTokenPair method instead.

**Comment by bob6664569** [comment]
Just simplified (again) the thing, will write some tests to make sure that everything is alright !

**Comment by bob6664569** [comment]
There is an issue with "IOTA", it is never associated with the "BTC" base, in `standardTokenSymbol`, `displayedTokenSymbol` or `aliasTokenSymbol`... But when fetching the current positions, the alias symbol is "IOTA"... 👎

**Comment by bob6664569** [comment]
I will stay to this [version](https://github.com/bob6664569/blockfolio-api-client/commit/4a907add87160e7336d410404386067dbf3d312c), be sure to use "standardTokenSymbol" when possible on the different calls.

Example (backup script)
```javascript
Blockfolio.init(BLOCKFOLIO_CLIENT_TOKEN).then(() => {
    return Blockfolio.getPositions();
}).then((positions) => {
    let positionsList = [], alertsList = [];
    console.log("Fetching datas for " + positions.length + " coins...");
    async.each(positions, (position, done) => {
        async.parallel(
            [
                (callback) => {
                    console.log(`- Fetching positions for ${position.standardTokenSymbol}/${position.base}...`);
                    Blockfolio.getPositions({ pair: {base: position.base, token: position.standardTokenSymbol} }).then((nPos) => {
                        nPos.forEach((sPos) => {
                            positionsList.push(sPos);
                        });
                        callback();
                    }).catch((err) => {
                        console.log (err);
                    });
                },
                (callback) => {
                    console.log(`- Fetching alerts for ${position.standardTokenSymbol}/${position.base}...`);
                    Blockfolio.getAlerts({base: position.base, token: position.standardTokenSymbol}).then((nAlerts) => {
                        nAlerts.forEach((sAlert) => {
                            alertsList.push(sAlert);
                        });
                        callback();
                    }).catch((err) => {
                        console.log (err);
                    });
                }
        ], (err) => {
            if (err) { return console.log(err); }
            done();
        });
    }, (err) => {
        if (err) { return console.log(err); }
        fs.writeFileSync("backup.json", JSON.stringify({positions: positionsList, alerts: alertsList}, null, 4), 'utf8');
        console.log("Done!");
    });
}).catch((err) => {
    console.error(err);
});
```
