### ISSUE TITLE
Downgrade to get deviceId not working anymore?

### ISSUE THREAD

**Issue by TimDaub** [bob6664569/blockfolio-api-client#10]
Hi,

I downgraded on Android as outlined in the tutorial to version 1.1.10 and got my token.
However it doesn't show my actual balance but the default balance if you had installed blockfolio back then (e.g. EOS, Tezos, etc.).

Any idea how to get my latest data?

**Comment by bob6664569** [comment]
Hi,

Sorry for the late reply, I was not available for updates until recently.

The downgrade procedure creates a new wallet, but once you get it, you can then upgrade back again, and use it the way you want, keeping the original token.

Anyway, I'll soon make an update to use the latest Blockfolio features, along with the new user/password login, that will make everything easier !
