### ISSUE TITLE
addPosition function doesn't have a parameter of date

### ISSUE THREAD

**Issue by johnnyasantoss** [bob6664569/blockfolio-api-client#3]
With this behaviour it is not possible to add historical transactions :confused:

**Comment by bob6664569** [comment]
I started to rewrite a new [addCoin](https://github.com/bob6664569/blockfolio-api-client/blob/develop/lib/blockfolio.js#L252)() method for v1.0.0 supporting every case possible, you can try to checkout the `develop` branch if you want to test it.

Every parameter is optional, and the following examples should be working with this version:

Simplest form:
```javascript
Blockfolio.addCoin("LTC", (err) => {
    if (err) return console.error(err);

    console.log("ETC successfully added to watchlist !");
});
```
All options used:
```javascript
Blockfolio.addCoin("STR/BTC",, {
        mode: "buy",
        exchange: "Bittrex",
        note: "Added some of them in 2015 at a good price !",
        price: 0.0015,
        amount: 42,
        timestamp: new Date("2015-12-17T03:24:00").getTime()
    }, (err) => {
    if (err) return console.error(err);

    console.log("STR successfully added !");
});
```
With promises and some options
```javascript
Blockfolio.addCoin("XMR", {
    mode: "buy",
    amount: 42,
    timestamp: new Date("1995-12-17T03:24:00").getTime()
}).then(() => {
    console.log("Transaction successfully added !");
}).catch((err) => {
    console.error(err);
});
```

You are welcome to send me some feedbacks as I think this will be the final form of this client lib :)

**Comment by johnnyasantoss** [comment]
Yes! Promises!
I'll probably look in to that, thanks in advance. I'm also making a fix for that method :)
