### ISSUE TITLE
Blockfolio.getPositions dosen't honor the first parameter

### ISSUE THREAD

**Issue by johnnyasantoss** [bob6664569/blockfolio-api-client#7]
This happens in the `beta2` version

**Comment by bob6664569** [comment]
The new `getPositions` must be called with an options object.

```javascript
getPositions({ pair: "XMR/USD" }).then(...)
```

Because the pair is not mandatory, and this method could be used to fetch all the global position with the following :

```javascript
getPositions().then(...)
```

... Much simpler !

**Comment by johnnyasantoss** [comment]
I've looked in the `develop` branch and it seems to be already fixed.
There was a problem with the value of `offsetPosition` in that function, but I ran `yarn upgrade` and it is fixed now :)

**Comment by bob6664569** [comment]
In fact, just saw that this method was the only one to have an object option for the coin as first parameter, so for unicity, I'll go back to a classical param (like `XMR`, `XMR/BTC` or `{base: "BTC, token: "XMR"}` without the object)
